language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.1"

before_script:
  - chmod +x gradlew

script:
  - ./gradlew testDebug
  - ./gradlew lint jacocoTestReportDebug detekt
  - ./gradlew sonarqube

after_success:
  - bash <(curl -s https://codecov.io/bash)